### ISSUE TITLE
Can't SSH to localhost, 127.0.0.1, or self ip

### ISSUE THREAD

**Issue by cowpod** [jakeajames/rootlessJB_EL#6]
Attempting to SSH in from the same device, results in an "Operation not permitted" when using terminus. SSHing in from another device works fine, however.

**Comment by level3tjg** [comment]
Install iSuperSU and give your SSH client permission.

**Comment by cowpod** [comment]
no change after clicking on one, two, or all permissions in iSuperSU.
Also I don't understand how giving the SSH client permission affects tcp..

**Comment by jakeajames** [comment]
to SSH to localhost you need to be unsandboxed

**Comment by cowpod** [comment]
thanks!
